### PR TITLE
[vrotsc] (#385) Fix TS-vRA archetype sample policy definition and re-add v2 policy attributes

### PR DESCRIPTION
**Pull request by bcpmihail**
### Description

Reintroduced the changes from https://github.com/vmware/build-tools-for-vmware-aria/pull/202 lost due to regression, causing sample policies from archetypes to fail.

Additional changes:
- cosmetic - brackets in switch/case
- fixed duplication of getEventType()

### Checklist

- [x] I have added relevant error handling and logging messages to help troubleshooting
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation, relevant usage information (if applicable)
- [x] I have updated the PR title with affected component, related issue number and a short summary of the changes introduced
- [x] I have added labels for implementation kind (kind/*) and version type (version/*)
- [x] I have tested against live environment, if applicable
- [x] I have synced any structure and/or content vRA-NG improvements with vra-ng and ts-vra-ng archetypes (if applicable)
- [x] I have my changes rebased and squashed to the minimal number of relevant commits. **Notice: don't squash all commits**
- [x] I have added a descriptive commit message with a short title, including a `Fixed #XXX -` or `Closed #XXX -` prefix to auto-close the issue

### Testing

Tested by building project from archetype, pushing to test environment.

### Related issues and PRs

https://github.com/vmware/build-tools-for-vmware-aria/issues/385
https://github.com/vmware/build-tools-for-vmware-aria/pull/202

### CODE REVIEW

**Comment by bcpmihail** [comment]
The variables do not translate to attributes. Working on it.

**Comment by bcpmihail** [comment]
As discussed with @Michaelpalacce , @VenelinBakalov , @joroaf :
- 'v1' will remain the default Policy Template version ('templateVersion' attribute), unless specified otherwise.
- the Policy template attributes will be validated, throwing an error when 'variables' or 'elements' are present for 'v1' (including when set by default) OR when 'type' is present for 'v2'.
- the samples in BTVA will be updated to 'v2'
- an issue will be opened for the next Major version milestone to make the 'templateVersion' attribute mandatory and update the sample Policy Template in https://github.com/vmware-samples/build-tools-for-vmware-aria-samples (will require major version release of the samples as well, as it won't be buildable with older BTVA versions like the base-package version 2.31.1 currently used there): pending link

**Comment by bcpmihail** [comment]
Added attribute version validation:
v2attrErr
v1attrErr

**Comment by Michaelpalacce** [comment]
Waiting to fix the build

**Comment by bcpmihail** [comment]
> > the samples in BTVA will be updated to 'v2'
> 
> I think we agreed to leave them to v1. What we can do is add more tests tho

As discussed, the samples in https://github.com/vmware-samples/build-tools-for-vmware-aria-samples will remain for v1, only the ones here were updated. The restored tests cover the new cases (which is why no new tests were added).

**Comment by bcpmihail** [comment]
> Waiting to fix the build

Re-running failed jobs (noticed this issue occurs when force-pushing a commit, like with the missed merge commit signature in this case)

**Review by Michaelpalacce — APPROVED** [review]
lgtm

**Pull request merged**
