### PR TITLE
Bumped maven plugin versions

### PR DESCRIPTION
**Pull request by joroaf**
### Checklist

- [x] Lint and unit tests pass locally with my changes
- [x] I have tested against a live environment, if applicable
- [x] I have added relevant usage information (As-built)
- [x] Any structure and/or content vRA-NG improvements are synchronized with vra-ng and ts-vra-ng archetypes
- [x] Dependencies in pom.xml are up-to-date
- [x] My changes have been rebased and squashed to the minimal number of relevant commits
- [x] My changes have a descriptive commit message with a short title, including a `Fixed #XXX -` or `Closed #XXX -` prefix to auto-close the issue

### Testing

* Building all project types is successful
* vrealize:push/vra-ng:pull against dev env

### Release Notes

Maven plugins bumped to the latest versions

### Related issues and PRs

#IAC-776 (HVA-2978)

### CODE REVIEW

**Comment by g-nikoloff** [comment]
I committed a minor update to the branch with another increase to a couple of versions. This can be merged into main now, deprecation warnings still exist for some of the modules used, but it is not possible to increase them due to other products we are interacting with at this point. (e.g. VCD)

**Comment by Michaelpalacce** [comment]
Fix should be done, need someone to test building,pushing,pulling with some archetypes

**Comment by Hristo-Cholakov** [comment]
> Fix should be done, need someone to test building,pushing,pulling with some archetypes

I'll give it a go!

**Review by ivo-kotev — APPROVED** [review]

**Comment by ivo-kotev** [comment]
> Fix should be done, need someone to test building,pushing,pulling with some archetypes

I building projects with the changes is already part of the CI process. On the push/pull side of the things, i hope this was tested during the changes were applied.

**Comment by joroaf** [comment]
vra/vro packages pull/push tested and working as expected. let's merge

**Review by ivo-kotev — APPROVED** [review]

**Pull request merged**
