### PR TITLE
[vro-types] (#458) Change `011n-plugin-vc` type declarations from interfaces to classes

### PR DESCRIPTION
**Pull request by VenelinBakalov**
### Checklist

- [ ] I have added relevant error handling and logging messages to help troubleshooting
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation, relevant usage information (if applicable)
- [x] I have updated the PR title with affected component, related issue number and a short summary of the changes introduced
- [x] I have added labels for implementation kind (kind/*) and version type (version/*)
- [x] I have tested against live environment, if applicable
- [ ] I have synced any structure and/or content vRA-NG improvements with vra-ng and ts-vra-ng archetypes (if applicable)
- [x] I have my changes rebased and squashed to the minimal number of relevant commits. **Notice: don't squash all commits**
- [x] I have added a descriptive commit message with a short title, including a `Fixed #XXX -` or `Closed #XXX -` prefix to auto-close the issue

### Related issues and PRs
#458

### CODE REVIEW

**Comment by VenelinBakalov** [comment]
@unbreakabl3 validated your Cluster case, builds successfully now

**Comment by VenelinBakalov** [comment]
Sample test:
image

**Comment by VenelinBakalov** [comment]
@unbreakabl3 things got a bit out of hand...but the end result should be good :D
Screenshot 2024-10-17 at 16 47 52

**Review by Michaelpalacce — APPROVED** [review]
lgtm

**Pull request merged**
