### PR TITLE
[vrotsc-types] (#347) Add aria plugin types definitions

### LINKED ISSUE #347: Add missing Aria types to `vro-types`
### Description

Take a look at `vro-types/o11n-plugin-aria`. There are a lot of type declarations that are missing. Based on what is visible in the Api Explorer, we need to fill in whatever is missing.

### PR DESCRIPTION
**Pull request by unbreakabl3**
### Description

Add missing classes to o11n-plugin-aria

### Checklist

- [ ] I have added relevant error handling and logging messages to help troubleshooting
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation, relevant usage information (if applicable)
- [x] I have updated the PR title with affected component, related issue number and a short summary of the changes introduced
- [x] I have added labels for implementation kind (kind/*) and version type (version/*)
- [ ] I have tested against live environment, if applicable
- [ ] I have synced any structure and/or content vRA-NG improvements with vra-ng and ts-vra-ng archetypes (if applicable)
- [ ] I have my changes rebased and squashed to the minimal number of relevant commits. **Notice: don't squash all commits**
- [x] I have added a descriptive commit message with a short title, including a `Fixed #XXX -` or `Closed #XXX -` prefix to auto-close the issue

### Related issues and PRs

https://github.com/vmware/build-tools-for-vmware-aria/issues/347

### CODE REVIEW

**Comment by VenelinBakalov** [comment]
@unbreakabl3 thanks, I checked the changes, everything looks good, there is just a merge conflict left.

Btw I saw that you are using the same branch for you PRs, probably that is the reason why merge conflicts arise because it gets outdated based on other PRs that are getting merged.

Usually I prefer to create separate branch for every feature I implement because it is created from the latest state of main and for me it is easier to handle. Of course, this does not guarantee that a merge conflict will arise. So it is kind of a personal preference whether you want to use one way or the other. So feel free to keep using the same branch if you prefer it this way. Should you decide to create separate branch, you can check the latest suggestion in the contribution guidelines under section -> Naming convention for branches (https://github.com/vmware/build-tools-for-vmware-aria/blob/main/CONTRIBUTING.md#contributing-code)

But again, this is just a suggestion if you decide to go this way, otherwise it is perfectly fine to keep your current approach as well, if it is more convenient for you.

**Review by VenelinBakalov — CHANGES_REQUESTED** [review]
Code changes looks good, just merge conflict left to resolve

**Comment by unbreakabl3** [comment]
> @unbreakabl3 thanks, I checked the changes, everything looks good, there is just a merge conflict left.
> 
> Btw I saw that you are using the same branch for you PRs, probably that is the reason why merge conflicts arise because it gets outdated based on other PRs that are getting merged.
> 
> Usually I prefer to create separate branch for every feature I implement because it is created from the latest state of main and for me it is easier to handle. Of course, this does not guarantee that a merge conflict will arise. So it is kind of a personal preference whether you want to use one way or the other. So feel free to keep using the same branch if you prefer it this way. Should you decide to create separate branch, you can check the latest suggestion in the contribution guidelines under section -> Naming convention for branches (https://github.com/vmware/build-tools-for-vmware-aria/blob/main/CONTRIBUTING.md#contributing-code)
> 
> But again, this is just a suggestion if you decide to go this way, otherwise it is perfectly fine to keep your current approach as well, if it is more convenient for you.

@VenelinBakalov, Thank you for your comment. Absolutely valuable. I think I did try to follow both ways and sometimes something went wrong. But I have no problem to create branches at all :). Will do next ime.

**Review by VenelinBakalov — APPROVED** [review]

**Comment by VenelinBakalov** [comment]
> > @unbreakabl3 thanks, I checked the changes, everything looks good, there is just a merge conflict left.
> > Btw I saw that you are using the same branch for you PRs, probably that is the reason why merge conflicts arise because it gets outdated based on other PRs that are getting merged.
> > Usually I prefer to create separate branch for every feature I implement because it is created from the latest state of main and for me it is easier to handle. Of course, this does not guarantee that a merge conflict will arise. So it is kind of a personal preference whether you want to use one way or the other. So feel free to keep using the same branch if you prefer it this way. Should you decide to create separate branch, you can check the latest suggestion in the contribution guidelines under section -> Naming convention for branches (https://github.com/vmware/build-tools-for-vmware-aria/blob/main/CONTRIBUTING.md#contributing-code)
> > But again, this is just a suggestion if you decide to go this way, otherwise it is perfectly fine to keep your current approach as well, if it is more convenient for you.
> 
> @VenelinBakalov, Thank you for your comment. Absolutely valuable. I think I did try to follow both ways and sometimes something went wrong. But I have no problem to create branches at all :). Will do next ime.

Sure thing :) however is more comfortable for you, both options are ok

**Pull request merged**
