### PR TITLE
[typescript/polyglotpkg] Add new PowerShell and PowerCLI runtime options

### PR DESCRIPTION
**Pull request by pe1pip**
change default to PowerCLI 13 with PowerShell 7.4

### Description

Update for supported PowerShell runtimes

### Checklist

- [x] I have added necessary documentation, relevant usage information (if applicable)

### Release Notes

[POLYGLOT] add support for recent PowerShell and PowerCLI

### CODE REVIEW

**Comment by Michaelpalacce** [comment]
This is breaking, unfortunately we can't merge it... we can add this to the 3.0.0 milestone

**Comment by VenelinBakalov** [comment]
Maybe we can split it in 2 - @Michaelpalacce only the default version is the breaking change right?
If yes, we can probably add an issue for that and mark it for 3.0.0 milestone
And for the extended runtime option we can still add them?

**Comment by Michaelpalacce** [comment]
I am ok with that @pe1pip, can you revert the "default" to what it was?

**Comment by pe1pip** [comment]
> I am ok with that @pe1pip, can you revert the "default" to what it was?

I did, note that on vRO 8.18 powerCLI 11/ powerShell 6.2 is no longer available, the oldest version is powerCLI 12 with powerShell 7.4

**Comment by VenelinBakalov** [comment]
@pe1pip looks good thanks, just one last note, please update the release md as well

**Comment by Michaelpalacce** [comment]
@VenelinBakalov @pe1pip  I am merging this and will create a new branch with the release.md

**Review by Michaelpalacce — APPROVED** [review]

**Pull request merged**
