### PR TITLE
[vrotsc] (#393) Make `versionTemplate` mandatory property of `@PolicyTemplate` decorator properties

### LINKED ISSUE #393: Make Policy Template version mandatory
### Description

Full support for the Policy Feature was introduced 2 via adding new attributes to the Policy Template:
- templateVersion
- elements
- variables 
and makes the 'type' attribute obsolete.

To take advantage of these improvements, 'templateVersion': 'v2' is required.
However this can be easily missed as  the attribute is optional and its value defaults to 'v1' (for backward compatibility).
To avoid missing on the new functionality or confusion with the available versions, the 'templateVersion' attribute needs to be made mandatory.

As the Policy Template attributes are validated, this will be a breaking change (affecting all Policies built), requiring Major version release for BTVA and for https://github.com/vmware-samples/build-tools-for-vmware-aria-samples, where the sample and base-package version need to be updated.

### Additional Context

The issue is opened after discussion in:
https://github.com/vmware/build-tools-for-vmware-aria/issues/385

Introduction of full support for the Policy Feature:
https://github.com/vmware/build-tools-for-vmware-aria/pull/20

### PR DESCRIPTION
**Pull request by Michaelpalacce**
### Description

This is a breaking change. The `versionTemplate` property for `@PolicyTemplate` decorators is now mandatory.

Error:

image

### Checklist

- [x] I have added relevant error handling and logging messages to help troubleshooting
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation, relevant usage information (if applicable)
- [x] I have updated the PR title with affected component, related issue number and a short summary of the changes introduced
- [x] I have added labels for implementation kind (kind/*) and version type (version/*)
- [x] I have tested against live environment, if applicable
- [x] I have synced any structure and/or content vRA-NG improvements with vra-ng and ts-vra-ng archetypes (if applicable)
- [x] I have my changes rebased and squashed to the minimal number of relevant commits. **Notice: don't squash all commits**
- [x] I have added a descriptive commit message with a short title, including a `Fixed #XXX -` or `Closed #XXX -` prefix to auto-close the issue

### Testing

Tests are green

### Related issues and PRs
Closes #393

### CODE REVIEW

**Comment by Michaelpalacce** [comment]
The build is failing expectedly, need to modify the samples

**Comment by VenelinBakalov** [comment]
we probably need to update this one as well:
https://github.com/vmware-samples/build-tools-for-vmware-aria-samples/pull/1

**Review by VenelinBakalov — CHANGES_REQUESTED** [review]
LGTM - I think we just need to update this PR and any possible samples reference to this change: https://github.com/vmware-samples/build-tools-for-vmware-aria-samples/pull/1

**Comment by Michaelpalacce** [comment]
@VenelinBakalov Yep, pretty much

**Review by VenelinBakalov — APPROVED** [review]

**Pull request merged**
