### PR TITLE
make schedule & scheduleRecurrently optional parameters optional

### PR DESCRIPTION
**Pull request by pe1pip**
### Description

the methods schedule & scheduleReccurently of the Workflow class were incorrect in making all parameters mandatory, apart from the properties all parameters are optional

### Checklist

- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added relevant error handling and logging messages to help troubleshooting
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] I have updated CHANGELOG.md with a short summary of the changes introduced
- [ ] I have tested against live environment, if applicable
- [ ] I have added relevant usage information (As-built)
- [ x] Any structure and/or content vRA-NG improvements are synchronized with vra-ng and ts-vra-ng archetypes
- [ x] Every new or updated Installer property is documented in docs/archive/doc/markdown/use-bundle-installer.md
- [ x] Dependencies in pom.xml are up-to-date
- [ x] My changes have been rebased and squashed to the minimal number of relevant commits
- [ x] My changes have a descriptive commit message with a short title, including a `Fixed #XXX -` or `Closed #XXX -` prefix to auto-close the issue

### CODE REVIEW

**Comment by Michaelpalacce** [comment]
image

For reference.

**Review by Michaelpalacce — CHANGES_REQUESTED** [review]
Lets update the CHANGELOG.md with the changes that were done in this branch.

Add a 

### Fixes
- [vro-types] [25](https://github.com/vmware/build-tools-for-vmware-aria/pull/25/files) make schedule & scheduleRecurrently optional parameters optional

Also go to https://github.com/vmware/build-tools-for-vmware-aria/blob/main/docs/versions/latest/Release.md

and add a new "Improvements" section that follows the following pattern:

[//]: # (### *Improvement Name* )
[//]: # (Talk ONLY regarding the improvement)
[//]: # (Optional But higlhy recommended)
[//]: # (#### Previous Behavior)
[//]: # (Explain how it used to behave, regarding to the change)
[//]: # (Optional But higlhy recommended)
[//]: # (#### New Behavior)
[//]: # (Explain how it behaves now, regarding to the change)
[//]: # (Optional But higlhy recommended Specify *NONE* if missing)
[//]: # (#### Relevant Documentation:)

**Comment by pe1pip** [comment]
> Lets update the CHANGELOG.md with the changes that were done in this branch.
> 
> Add a
> 
> ### Fixes
> * [vro-types] [25](https://github.com/vmware/build-tools-for-vmware-aria/pull/25/files) make schedule & scheduleRecurrently optional parameters optional
> 
> Also go to https://github.com/vmware/build-tools-for-vmware-aria/blob/main/docs/versions/latest/Release.md
> 
> and add a new "Improvements" section that follows the following pattern:

done

**Comment by Michaelpalacce** [comment]
Still need to do:

Also go to https://github.com/vmware/build-tools-for-vmware-aria/blob/main/docs/versions/latest/Release.md

and add a new "Improvements" section that follows the following pattern:

And I can approve it

**Comment by pe1pip** [comment]
> 

Hi,

I looked at the file and found the improvements section, but need some more guidance, what do all these characters mean? Is there some url where I can find a working example?

**Comment by Michaelpalacce** [comment]
https://github.com/vmware/build-tools-for-vmware-aria/blob/main/docs/versions/v2.29.1/Release.md

You can Check Out a previous release.

And those are markdown comments ( the ones in the latest release )

**Review by Michaelpalacce — APPROVED** [review]
Looks good to me

**Comment by Michaelpalacce** [comment]
@pe1pip You can merge with master to resolve the conflicts and we can merge this branch

**Pull request closed without merging**
